In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_breast_cancer

In [3]:
data = load_breast_cancer(as_frame=True)
df = data.frame

In [4]:
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [5]:
df.shape

(569, 31)

In [6]:
data.DESCR

'.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 569\n\n:Number of Attributes: 30 numeric, predictive attributes and the class\n\n:Attribute Information:\n    - radius (mean of distances from center to points on the perimeter)\n    - texture (standard deviation of gray-scale values)\n    - perimeter\n    - area\n    - smoothness (local variation in radius lengths)\n    - compactness (perimeter^2 / area - 1.0)\n    - concavity (severity of concave portions of the contour)\n    - concave points (number of concave portions of the contour)\n    - symmetry\n    - fractal dimension ("coastline approximation" - 1)\n\n    The mean, standard error, and "worst" or largest (mean of the three\n    worst/largest values) of these features were computed for each image,\n    resulting in 30 features.  For instance, field 0 is Mean Radius, field\n    10 is Radius SE, field 20 is Worst Radius.\n\n    - class:\n            - WDBC-Malignant\n            - WDBC-Benign\n\n:Summary Statistics:\n\n===================================== ====== ======\n                                        Min    Max\n===================================== ====== ======\nradius (mean):                        6.981  28.11\ntexture (mean):                       9.71   39.28\nperimeter (mean):                     43.79  188.5\narea (mean):                          143.5  2501.0\nsmoothness (mean):                    0.053  0.163\ncompactness (mean):                   0.019  0.345\nconcavity (mean):                     0.0    0.427\nconcave points (mean):                0.0    0.201\nsymmetry (mean):                      0.106  0.304\nfractal dimension (mean):             0.05   0.097\nradius (standard error):              0.112  2.873\ntexture (standard error):             0.36   4.885\nperimeter (standard error):           0.757  21.98\narea (standard error):                6.802  542.2\nsmoothness (standard error):          0.002  0.031\ncompactness (standard error):         0.002  0.135\nconcavity (standard error):           0.0    0.396\nconcave points (standard error):      0.0    0.053\nsymmetry (standard error):            0.008  0.079\nfractal dimension (standard error):   0.001  0.03\nradius (worst):                       7.93   36.04\ntexture (worst):                      12.02  49.54\nperimeter (worst):                    50.41  251.2\narea (worst):                         185.2  4254.0\nsmoothness (worst):                   0.071  0.223\ncompactness (worst):                  0.027  1.058\nconcavity (worst):                    0.0    1.252\nconcave points (worst):               0.0    0.291\nsymmetry (worst):                     0.156  0.664\nfractal dimension (worst):            0.055  0.208\n===================================== ====== ======\n\n:Missing Attribute Values: None\n\n:Class Distribution: 212 - Malignant, 357 - Benign\n\n:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n:Donor: Nick Street\n\n:Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. dropdown:: References\n\n  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction\n    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on\n    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n    San Jose, CA, 1993.\n  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and\n    prognosis via linear programming. Operations Research, 43(4), pages 570-577,\n    July-August 1995.\n  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)\n    163-171.\n'

In [7]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         569 non-null    float64
 15  compactness error        569 non-null    float64
 16  concavity error          569 non-null    float64
 17  concave points error     569 non-null    float64
 18  symmetry error           569 non-null    float64
 19  fractal dimension error  569 non-null    float64
 20  worst radius             569 non-null    float64
 21  worst texture            569 non-null    float64
 22  worst perimeter          569 non-null    float64
 23  worst area               569 non-null    float64
 24  worst smoothness         569 non-null    float64
 25  worst compactness        569 non-null    float64
 26  worst concavity          569 non-null    float64
 27  worst concave points     569 non-null    float64
 28  worst symmetry           569 non-null    float64
 29  worst fractal dimension  569 non-null    float64
 30  target                   569 non-null    int64
dtypes: float64(30), int64(1)
memory usage: 137.9 KB

In [9]:
X = df.drop("target", axis=1)
y = df["target"]

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=15)

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
scaler = StandardScaler()

In [13]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
columns = data.feature_names

In [15]:
X_train = pd.DataFrame(X_train, columns=columns)

In [16]:
X_train

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,0.083873,-0.983504,0.077016,-0.048605,0.221698,-0.051884,-0.060168,0.161591,-0.346668,-0.305506,...,-0.085581,-0.966340,0.034735,-0.201125,-0.048765,0.127497,0.181973,0.692247,-0.352364,-0.410313
1,-0.098493,-0.836530,-0.147500,-0.197898,-0.613975,-0.716869,-0.975662,-1.003775,-1.492869,-0.633109,...,-0.203450,-1.357382,-0.277513,-0.305135,-1.140546,-0.953456,-1.143545,-1.241889,-1.650695,-0.909548
2,-0.109546,-0.325735,-0.157523,-0.200377,-1.246710,-0.781996,-0.750730,-0.917676,-1.248538,-1.009923,...,-0.189225,-0.532034,-0.298232,-0.271845,-1.592025,-0.464299,-0.559484,-0.828913,-0.884492,-0.792888
3,-0.267045,-0.145029,-0.243320,-0.339202,1.388597,0.348021,0.404600,0.625858,1.104948,0.673085,...,-0.122161,0.381507,-0.134521,-0.214061,2.054257,1.057091,1.098798,1.438258,1.534273,1.938320
4,0.680711,2.124638,0.651537,0.551871,-0.876346,-0.048075,0.033943,0.102530,-0.828144,-0.914314,...,0.550504,1.408201,0.562929,0.414834,-0.840754,0.360708,0.326507,0.416116,-1.090477,-0.331968
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,1.194654,-0.178760,1.164716,1.149318,0.152119,0.009054,0.538869,0.999480,1.119321,-0.388462,...,1.353231,0.336579,1.307070,1.241056,0.318145,-0.292152,0.207989,0.757847,1.214372,0.102075
422,0.086637,0.230840,0.097864,-0.041443,0.150670,0.300413,0.347936,0.276631,0.465375,0.235812,...,0.418409,0.742597,0.306127,0.276842,1.007221,0.985634,1.080009,1.056862,2.865374,0.989031
423,0.979129,0.356129,1.016375,0.842744,1.076941,1.174491,1.179419,1.447569,0.540830,-0.185994,...,0.853305,-0.091071,0.743857,0.721864,0.407636,0.623151,0.413227,0.564098,-0.708156,-0.378861
424,-0.236650,-1.335278,-0.250937,-0.319370,-0.943026,-0.363239,-0.480221,-0.523511,-0.731130,-0.990239,...,-0.412769,-1.379014,-0.315741,-0.448129,-0.719942,0.095017,0.067792,-0.347744,-0.282142,-0.617899
425,-0.692567,2.416177,-0.688743,-0.668363,-0.222593,-0.363429,-0.223632,-0.741008,-0.077184,-0.185994,...,-0.640378,2.188621,-0.623611,-0.613546,0.353941,-0.329829,0.095253,-0.704425,-0.051189,-0.675085

In [17]:
X_test = pd.DataFrame(X_test, columns=columns)

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier

In [19]:
logistic = LogisticRegression()
gbc = GradientBoostingClassifier()

In [20]:
logistic.fit(X_train, y_train)
gbc.fit(X_train, y_train)

GradientBoostingClassifier()

In [21]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [22]:
print("logistic regression")
y_pred_logistic = logistic.predict(X_test)
print(accuracy_score(y_test, y_pred_logistic))
print(confusion_matrix(y_test, y_pred_logistic))
print(classification_report(y_test, y_pred_logistic))

print("-----------------------")

print("gradient boosting classifier")
y_pred_gbc = gbc.predict(X_test)
print(accuracy_score(y_test, y_pred_gbc))
print(confusion_matrix(y_test, y_pred_gbc))
print(classification_report(y_test, y_pred_gbc))

logistic regression
0.958041958041958
[[49  4]
 [ 2 88]]
              precision    recall  f1-score   support

           0       0.96      0.92      0.94        53
           1       0.96      0.98      0.97        90

    accuracy                           0.96       143
   macro avg       0.96      0.95      0.95       143
weighted avg       0.96      0.96      0.96       143

-----------------------
gradient boosting classifier
0.9440559440559441
[[46  7]
 [ 1 89]]
              precision    recall  f1-score   support

           0       0.98      0.87      0.92        53
           1       0.93      0.99      0.96        90

    accuracy                           0.94       143
   macro avg       0.95      0.93      0.94       143
weighted avg       0.95      0.94      0.94       143

In [23]:
from sklearn.decomposition import PCA

In [24]:
pca=PCA()

In [25]:
pca = PCA(n_components=4)

In [26]:
X_train_pca=pca.fit_transform(X_train)
X_test_pca=pca.transform(X_test)

In [27]:
X_train_pca = pd.DataFrame(X_train_pca, columns=["PCA 1", "PCA 2", "PCA 3", "PCA 4"])
X_test_pca = pd.DataFrame(X_test_pca, columns=["PCA 1", "PCA 2", "PCA 3", "PCA 4"])

In [28]:
X_train_pca

        PCA 1     PCA 2     PCA 3     PCA 4
0   -0.478413 -0.480238 -0.905738 -1.388936
1   -3.476482 -2.219422  0.405915 -1.473204
2   -3.054738 -2.309091 -0.288076 -0.074841
3    1.628649  2.254628 -3.204102 -0.170868
4    1.231041 -1.899407  0.541593  2.300880
..        ...       ...       ...       ...
421  3.158756 -1.599216  0.059319 -0.434105
422  1.182785  0.278223 -3.902022  0.533188
423  3.986776 -0.321750  1.385298 -0.654037
424 -2.341799 -1.050465 -0.937970 -1.423930
425 -1.264204  0.782168  1.090103  3.880211

[426 rows x 4 columns]

In [29]:
logistic = LogisticRegression()
gbc = GradientBoostingClassifier()

In [30]:
logistic.fit(X_train_pca, y_train)
gbc.fit(X_train_pca, y_train)

GradientBoostingClassifier()

In [31]:
print("logistic regression")
y_pred_logistic = logistic.predict(X_test_pca)
print(accuracy_score(y_test, y_pred_logistic))
print(confusion_matrix(y_test, y_pred_logistic))
print(classification_report(y_test, y_pred_logistic))

print("-----------------------")

print("gradient boosting classifier")
y_pred_gbc = gbc.predict(X_test_pca)
print(accuracy_score(y_test, y_pred_gbc))
print(confusion_matrix(y_test, y_pred_gbc))
print(classification_report(y_test, y_pred_gbc))

logistic regression
0.9370629370629371
[[48  5]
 [ 4 86]]
              precision    recall  f1-score   support

           0       0.92      0.91      0.91        53
           1       0.95      0.96      0.95        90

    accuracy                           0.94       143
   macro avg       0.93      0.93      0.93       143
weighted avg       0.94      0.94      0.94       143

-----------------------
gradient boosting classifier
0.916083916083916
[[48  5]
 [ 7 83]]
              precision    recall  f1-score   support

           0       0.87      0.91      0.89        53
           1       0.94      0.92      0.93        90

    accuracy                           0.92       143
   macro avg       0.91      0.91      0.91       143
weighted avg       0.92      0.92      0.92       143

In [ ]:
X = df.drop("target", axis=1)

In [ ]:
scaler = StandardScaler()

In [ ]:
scaler.fit_transform(X)

In [ ]:
pca = PCA(n_components=2)

In [ ]:
X = pca.fit_transform(X)

In [ ]:
X = pd.DataFrame(X, columns=["PC1", "PC2"])

In [ ]:
sns.scatterplot(data = X, x = "PC1", y = "PC2", hue=df["target"])
plt.show()